import { NumberGrid } from '../grid/NumberGrid';

/**
 * This tools is aimed at replacing pattern of cell codes generated by world generator
 * So we can have more diversity in level sceneries
 * The principe is simple :
 * Some kind of convolution iteration will recognize simple patterns in the specified map, and will replace them by
 * another, likely more diverse and complex, pattern.
 */

type PatternDefinition = { [char: string]: number[] };
type CharMap = string[][];
export type PatternSearchAndReplace = {
    // This is a dictionnary of Symbol -> Cell codes
    patternDefinitions: PatternDefinition;
    replaceDefinitions: PatternDefinition;
    patternSearch: CharMap;
    replaceBy: CharMap;
};

export class PatternMapRefiner {
    constructor(
        private patterns: PatternSearchAndReplace[],
        private numberMap: NumberGrid
    ) {}
}
