import { NumberGrid } from '../grid/NumberGrid';
import { CoordinateList } from '../../types/CoordinateList';

/**
 * This tools is aimed at replacing pattern of cell codes generated by world generator
 * So we can have more diversity in level sceneries
 * The principe is simple :
 * Some kind of convolution iteration will recognize simple patterns in the specified map, and will replace them by
 * another, likely more diverse and complex, pattern.
 *
 */
const ANY_PATTERN = '?';
const ANY_REPLACEMENT = '?';
type CodePalette = { [char: string]: number[] };
type PatternMap = string[];

export class PatternMapRefiner {
    constructor(
        private readonly palette: CodePalette,
        private readonly numberMap: NumberGrid
    ) {}

    /**
     * Register all places in the grid where the specified pattern is found.
     *
     * Each character in the pattern rows is looked up in the palette; the cell
     * value at that position must be one of the listed values.
     * The special character ANY_PATTERN ('?') matches any cell value.
     * Characters not present in the palette also match any value.
     *
     * Returns the top-left coordinate of every matching area.
     */
    searchAllPatterns(search: PatternMap): CoordinateList {
        if (search.length === 0) {
            return [];
        }
        const patH = search.length;
        const patW = search[0].length;
        if (patW === 0) {
            return [];
        }
        const result: CoordinateList = [];
        for (let y = 0; y <= this.numberMap.height - patH; y++) {
            for (let x = 0; x <= this.numberMap.width - patW; x++) {
                if (this._matches(x, y, search, patW, patH)) {
                    result.push({ x, y });
                }
            }
        }
        return result;
    }

    /**
     * In the numberMap, Replace the specified pattern by another one
     * @param x coordinate, 0-based upper left corner of the pattern
     * @param y coordinate, 0-based upper left corner of the replacement pattern
     * @param pattern the pattern to apply
     *
     * Each character is looked up in the palette; the first value in the list
     * is written to the grid at that position.
     * The special character ANY_REPLACEMENT ('?') leaves the cell unchanged.
     * Characters not present in the palette are also left unchanged.
     */
    replaceAt(x: number, y: number, pattern: PatternMap): void {
        for (let dy = 0; dy < pattern.length; dy++) {
            const row = pattern[dy];
            for (let dx = 0; dx < row.length; dx++) {
                const char = row[dx];
                if (char === ANY_REPLACEMENT) {
                    continue;
                }
                const values = this.palette[char];
                if (values === undefined || values.length === 0) {
                    continue;
                }
                this.numberMap.setCellValue(x + dx, y + dy, values[0]);
            }
        }
    }

    /**
     * Replace all patterns in the numberMap by another one
     * @param search
     */
    replaceAllPatterns(search: Map<PatternMap, PatternMap>): void {
        for (const [pattern, replacement] of search) {
            const coords = this.searchAllPatterns(pattern);
            for (const { x, y } of coords) {
                this.replaceAt(x, y, replacement);
            }
        }
    }

    // ── Internal ──────────────────────────────────────────────────────────────

    private _matches(
        ox: number,
        oy: number,
        pattern: PatternMap,
        patW: number,
        patH: number
    ): boolean {
        for (let dy = 0; dy < patH; dy++) {
            const row = pattern[dy];
            for (let dx = 0; dx < patW; dx++) {
                const char = row[dx];
                if (char === ANY_PATTERN) {
                    continue;
                }
                const allowed = this.palette[char];
                if (allowed === undefined) {
                    continue; // unknown char = wildcard
                }
                const value = this.numberMap.getCellValue(ox + dx, oy + dy);
                if (value === undefined || !allowed.includes(value)) {
                    return false;
                }
            }
        }
        return true;
    }
}
