import { AnimationDefinition } from './AnimationRunner';
import { ISeededRNG } from '../libs/mulberry32/ISeededRNG';
import { ITileRenderer } from '../tile-renderer/ITileRenderer';
import { IWorldGenerator } from '../world-generator/IWorldGenerator';
import { PhysicsCell } from './physics-types';

export type CoordinateList = { x: number; y: number }[];

/**
 * This type of layer is dedicated to tilemaps
 */
export type TileMapLayerDefinition = {
    key: string;
    zIndex: number;
    tileMap: number[][]; // The real map data
    physicsMap: PhysicsCell[][] | null; // Physical properties per cell (solid, transparent, tags)
    animatedTiles: Record<string, CoordinateList>;
    texture: HTMLCanvasElement; // The tileset image
    tileSize: number; // size of a tile in pixels
    tilesetWidth: number; // number of tiles in a row
    tilesetHeight: number; // number of tiles in a column
    scrollFactor: number; // 1 = scroll with camera, 0 = no scroll, 0.5 = parallax scrolling, all values accepted
    animations: AnimationDefinition[];
};

/**
 * Glossary :
 * - Cell : a numeric code produced by a world generator
 * - Tile : a numeric code produced by a tile renderer, indexing a texture
 * - Animation : a structure that describe a tile animation. This kind of animation will rotate
 * through a collection of tiles to animate the corresponding block.
 *
 * This structure associates a cell code (generated by a world generator)
 * with a choice of tiles or animation.
 * additionally, a registry of custom attributes may be specified to add some
 * mechanic semantics to the worldblock
 */
export type WorldBlock = {
    cell: number;
    tiles: number[];
    animations: string[];
    attributes?: Record<string, number>;
    tags?: string[];
};

export type { PhysicsCell };

class WorldBuilder {
    constructor(
        private readonly worldBlocks: WorldBlock[],
        private readonly animationDefinitions: AnimationDefinition[],
        private readonly tileIndexRegistry: Map<number, number>,
        private readonly rng: ISeededRNG
    ) {}

    /**
     * given a world block, will choose between tiles and animations
     * returns tile index and/or animation key
     * @param wb
     */
    selectTileAnimation(wb: WorldBlock): { tile: number; animation: string } {
        const tlen = wb.tiles.length;
        const alen = wb.animations.length;
        const i = this.rng.nextInt(0, tlen + alen - 1);
        if (i >= tlen) {
            // animation : we must include the first tile of the animation
            const animKey = wb.animations[i - tlen];
            if (animKey !== undefined) {
                const ad = this.animationDefinitions.find((a) => a.key === animKey);
                if (ad) {
                    const iTile = this.tileIndexRegistry.get(ad.frames[0] ?? 0);
                    if (iTile === undefined) {
                        throw new ReferenceError(
                            `Animation key ${animKey} references a tile code that is not in the tile index registry ${ad.frames[0] ?? 0}. This is a bug in the world composer.`
                        );
                    }
                    return {
                        tile: iTile,
                        animation: animKey,
                    };
                } else {
                    throw new ReferenceError(
                        `Unknown animation key: ${animKey}. Specified in world block def, but does not match any layerDefinition animations keys`
                    );
                }
            } else {
                throw new RangeError(
                    `Picked up item ${i - tlen} from world block animations, but out-of-range, or undefined in-range item.`
                );
            }
        } else {
            // tile : we don't use animation
            return { tile: wb.tiles[i] ?? 0, animation: '' };
        }
    }

    /**
     * Will use a collection of world block, a cell map, and a tile registry to build a world
     * and incorporate it in a WorldScene.
     * @param cellMap
     */
    buildWorld(cellMap: number[][]): {
        tileMap: number[][];
        animations: Map<string, CoordinateList>;
        physicsMap: PhysicsCell[][];
    } {
        const wbRegistry = new Map<number, WorldBlock>(this.worldBlocks.map((w) => [w.cell, w]));
        const tileMapOutput: number[][] = [];
        const physicsMapOutput: PhysicsCell[][] = [];
        const animationOutput = new Map<string, CoordinateList>();
        for (let y = 0, h = cellMap.length; y < h; ++y) {
            const cellRow = cellMap[y];
            const tmoRow: number[] = [];
            const pmoRow: PhysicsCell[] = [];
            for (let x = 0, w = cellRow.length; x < w; ++x) {
                const cell = cellRow[x];
                const wb = wbRegistry.get(cell);
                if (wb) {
                    // World block matching cell, found.
                    // choose a tile or an animation
                    const { tile, animation } = this.selectTileAnimation(wb);
                    if (animation !== '') {
                        const ao = animationOutput.get(animation);
                        if (ao) {
                            ao.push({ x, y });
                        } else {
                            animationOutput.set(animation, [{ x, y }]);
                        }
                    }
                    tmoRow.push(tile);
                    pmoRow.push({
                        solid: (wb.attributes?.solid ?? 0) > 0,
                        transparent: (wb.attributes?.transparent ?? 0) > 0,
                        tags: wb.tags ?? [],
                    });
                } else {
                    pmoRow.push({
                        solid: false,
                        transparent: false,
                        tags: [],
                    });
                }
            }
            tileMapOutput.push(tmoRow);
            physicsMapOutput.push(pmoRow);
        }
        return {
            tileMap: this.convertTileCodeToIndex(tileMapOutput),
            animations: animationOutput,
            physicsMap: physicsMapOutput,
        };
    }

    /**
     * Creates a new version of the tile map, replacing all tile codes by their respective tile index.
     * all invalid tile codes lead to a 0 index
     * @param tileMap
     */
    convertTileCodeToIndex(tileMap: number[][]): number[][] {
        return tileMap.map((row) => row.map((tile) => this.tileIndexRegistry.get(tile) ?? 0));
    }
}

export function buildLayerDefinition(
    rng: ISeededRNG,
    key: string,
    zIndex: number,
    worldBlocks: WorldBlock[],
    animations: AnimationDefinition[],
    scrollFactor: number,
    tileRenderer: ITileRenderer,
    worldGenerator: IWorldGenerator,
    physic: boolean
): TileMapLayerDefinition {
    const tileIndex = tileRenderer.getTileIndexRegistry();
    const fixedAnimations = animations.map((a) => {
        return {
            ...a,
            frames: a.frames.map((f) => tileIndex.get(f) ?? 0),
        };
    });
    const wc = new WorldBuilder(worldBlocks, fixedAnimations, tileIndex, rng);
    const map = worldGenerator.generate();
    const { tileMap: md, animations: mdAnimations, physicsMap: mdPhysics } = wc.buildWorld(map);
    const rAnimTiles: Record<string, CoordinateList> = {};
    mdAnimations.forEach((value: CoordinateList, key: string) => {
        rAnimTiles[key] = value;
    });
    return {
        key,
        zIndex,
        scrollFactor,
        tileMap: md,
        physicsMap: physic ? mdPhysics : null,
        texture: tileRenderer.buildTileset(),
        tileSize: tileRenderer.tileSize,
        tilesetWidth: worldGenerator.width,
        tilesetHeight: worldGenerator.height,
        animations: fixedAnimations,
        animatedTiles: rAnimTiles,
    };
}
