import { TileMapLayerDefinition, WorldScene } from '../world-scene/WorldScene';
import { CrackPlanetWG } from '../world-generator/CrackPlanetWG';
import { AstroTileRenderer } from '../tile-renderer/themes/astro/AstroTileRenderer';
import { DeepSpaceWG } from '../world-generator/DeepSpaceWG';
import { DeepSpaceTileRenderer } from '../tile-renderer/themes/astro/DeepSpaceTileRenderer';
import { createRNGFromString } from '../libs/mulberry32';
import { IWorldGenerator } from '../world-generator/IWorldGenerator';
import { ITileRenderer } from '../tile-renderer/ITileRenderer';
import { ISeededRNG } from '../libs/mulberry32/ISeededRNG';
import { AnimationDefinition } from '../world-scene/AnimationRunner';

type CellTile = {
    cell: number;
    tiles: number[];
    animation: string;
};

/**
 * Glossary :
 * - Cell : a numeric code produced by a world generator
 * - Tile : a numeric code produced by a tile renderer, indexing a texture
 * - Animation : a structure that describe a tile animation. This kind of animation will rotate
 * through a collection of tiles to animate the corresponding block.
 *
 * This structure associates a cell code (generated by a world generator)
 * with a choice of tiles or animation.
 * additionally, a registry of custom attributes may be specified to add some
 * mechanic semantics to the worldblock
 */
type WorldBlock = {
    cell: number;
    tiles: number[];
    animations: string[];
    attributes?: Record<string, number>;
};

type CoordinateList = { x: number; y: number }[];

class WorldComposer {
    constructor(
        private readonly worldBlocks: WorldBlock[],
        private readonly animationDefinitions: AnimationDefinition[],
        private readonly tileIndexRegistry: Map<number, number>,
        private readonly rng: ISeededRNG
    ) {}

    /**
     * given a world block, will choose between tiles and animations
     * returns tile index and/or animation key
     * @param wb
     */
    selectTileAnimation(wb: WorldBlock): { tile: number; animation: string } {
        const tlen = wb.tiles.length;
        const alen = wb.animations.length;
        const i = this.rng.nextInt(0, tlen + alen - 1);
        if (i >= tlen) {
            // animation : we must include the first tile of the animation
            const animKey = wb.animations[i - tlen];
            if (animKey !== undefined) {
                const ad = this.animationDefinitions.find((a) => a.key === animKey);
                if (ad) {
                    return {
                        tile: ad.frames[0] ?? 0,
                        animation: animKey,
                    };
                } else {
                    throw new ReferenceError(
                        `Unknown animation key: ${animKey}. Specified in world block def, but does not match any layerDefinition animations keys`
                    );
                }
            } else {
                throw new RangeError(
                    `Picked up item ${i - tlen} from world block animations, but out-of-range, or undefined in-range item.`
                );
            }
        } else {
            // tile : we don't use animation
            return { tile: wb.tiles[i] ?? 0, animation: '' };
        }
    }

    /**
     * Will use a collection of world block, a cell map, and a tile registry to build a world
     * and incorporate it in a WorldScene.
     * @param cellMap
     */
    buildWorld(cellMap: number[][]) {
        const wbRegistry = new Map<number, WorldBlock>(this.worldBlocks.map((w) => [w.cell, w]));
        const tileMapOutput: number[][] = [];
        const animationOutput = new Map<string, CoordinateList>();
        for (let y = 0, h = cellMap.length; y <= h; ++y) {
            const cellRow = cellMap[y];
            const tmoRow: number[] = [];
            for (let x = 0, w = cellRow.length; x <= w; ++x) {
                const cell = cellRow[x];
                const wb = wbRegistry.get(cell);
                if (wb) {
                    // World block matching cell, found.
                    // choose a tile or an animation
                    const { tile, animation } = this.selectTileAnimation(wb);
                    if (animation !== '') {
                        const ao = animationOutput.get(animation);
                        if (ao) {
                            ao.push({ x, y });
                        } else {
                            animationOutput.set(animation, [{ x, y }]);
                        }
                    }
                    tmoRow.push(tile);
                }
            }
            tileMapOutput.push(tmoRow);
        }
        return {
            tileMap: this.convertTileCodeToIndex(tileMapOutput),
            animations: animationOutput,
        };
    }

    /**
     * Creates a new version of the tile map, replacing all tile codes by their respective tile index.
     * all invalid tile codes lead to a 0 index
     * @param tileMap
     */
    convertTileCodeToIndex(tileMap: number[][]): number[][] {
        return tileMap.map((row) => row.map((tile) => this.tileIndexRegistry.get(tile) ?? 0));
    }
}

export class Level01 extends WorldScene {
    private rng = createRNGFromString('level-1');
    private cpWorldBlocks: WorldBlock[] = [
        {
            cell: 0,
            tiles: [0],
            animations: [],
        },
        {
            cell: 1,
            tiles: [10, 11, 12, 13],
            animations: [],
        },
        {
            cell: 2,
            tiles: [20, 21, 22, 23],
            animations: [],
        },
        {
            cell: 3,
            tiles: [3],
            animations: [],
        },
        {
            cell: 4,
            tiles: [],
            animations: ['space-anomaly'],
        },
    ];
    private cpAnimations: AnimationDefinition[] = [
        {
            key: 'space-anomaly',
            duration: 1000,
            frames: [40, 41, 42, 43],
            repeat: Infinity,
            yoyo: true,
        },
    ];
    private dsWorldBlocks: WorldBlock[] = [
        {
            cell: 0,
            tiles: [10, 11, 12, 13],
            animations: [],
        },
        {
            cell: 1,
            tiles: [20, 21, 22, 23],
            animations: [],
        },
    ];
    private dsAnimations: AnimationDefinition[] = [];

    constructor() {
        super({
            key: 'Level01',
        });
    }

    buildLevelData(
        key: string,
        zIndex: number,
        worldBlocks: WorldBlock[],
        animations: AnimationDefinition[],
        scrollFactor: number,
        tileRenderer: ITileRenderer,
        worldGenerator: IWorldGenerator<number>
    ) {
        const tileMap: number[][] = [];
        const layerDefinition: TileMapLayerDefinition = {
            key,
            zIndex,
            tileMap: worldGenerator.generate(),
            texture: tileRenderer.buildTileset(),
            tileSize: tileRenderer.tileSize,
            tilesetWidth: worldGenerator.width,
            tilesetHeight: worldGenerator.height,
            scrollFactor,
            animations,
        };
    }

    create() {
        this.layerDefinitions = [
            {
                key: 'foreground',
                zIndex: 10,
                tileMap: md,
                texture: cptr.buildTileset(),
                tileSize: cptr.tileSize,
                tilesetWidth: cpwg.worldWidth,
                tilesetHeight: cpwg.worldHeight,
                scrollFactor: 1,
                animations: [
                    {
                        key: 'space-anomaly',
                        duration: 1000,
                        frames: [40, 41, 42, 43],
                        repeat: Infinity,
                        yoyo: true,
                    },
                ],
            },
            {
                key: 'deepspace',
                zIndex: 5,
                tileMap: dsmd,
                texture: dstr.buildTileset(),
                tileSize: dstr.tileSize,
                tilesetWidth: dswg.worldWidth,
                tilesetHeight: dswg.worldHeight,
                scrollFactor: 0.5,
                animations: [],
            },
        ];

        // Crack planet layer
        const cpwg = new CrackPlanetWG(this.rng, 200, 200);
        const cptr = new AstroTileRenderer();
        const cpwc = new WorldComposer(this.cpWorldBlocks);
        const dswg = new DeepSpaceWG(this.rng, 100, 100);
        const dstr = new DeepSpaceTileRenderer();

        // const { tileMap: md, animatedTiles } = this.buildTileMap(tr, wg, []);
        // const dsmd = this.buildTileMap(dstr, dswg, []);

        super.create();
    }

    buildTileMap(
        tileRenderer: ITileRenderer,
        worldGenerator: IWorldGenerator<number>,
        cellTiles: CellTile[]
    ): { tileMap: number[][]; animatedTiles: Map<string, { x: number; y: number }[]> } {
        const cellMap = worldGenerator.generate();
        const cellTileRegistry = new Map<number, { tiles: number[]; animation?: string }>();
        const animatedTileRegistry = new Map<string, { x: number; y: number }[]>();
        cellTiles.forEach((ct: CellTile) => {
            cellTileRegistry.set(ct.cell, {
                tiles: ct.tiles,
                animation: ct.animation,
            });
            if (ct.animation) {
                animatedTileRegistry.set(ct.animation, []);
            }
        });

        const animatedTiles = new Map<string, { x: number; y: number }[]>();
        const tileIndexRegistry = tileRenderer.getTileIndexRegistry();
        const tileMap = cellMap.map((row, y) =>
            row.map((cell, x) => {
                const { tiles: cellTiles, animation } = cellTileRegistry.get(cell) ?? {
                    tiles: [],
                    animation: '',
                };
                const tileId =
                    cellTiles.length > 0 ? cellTiles[this.rng.nextInt(0, cellTiles.length)] : 0;
                return tileIndexRegistry.get(tileId) ?? 0;
            })
        );

        return { tileMap, animatedTiles };
    }
}
